@namespace
class SpriteKind:
    objeto = SpriteKind.create()

def on_overlap_tile(sprite, location):
    if Wario.tile_kind_at(TileDirection.RIGHT,
        assets.tile("""
            miMosaico13
            """)):
        game.game_over(True)
    else:
        tiles.set_wall_at(location, True)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        miMosaico13
        """),
    on_overlap_tile)

def on_right_pressed():
    animation.run_image_animation(Wario,
        [img("""
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ........ffffffff..........
                ........22222222..........
                ....ffffffffffffffff......
                ........eeedddfd..........
                .......ededdddfdddd.......
                .......edeeddddfdddd......
                .......ededdddfffff.......
                ......ffeddddddddd........
                .....f221111111112f.......
                .....f21ffffffff11f.......
                ....f22ffffffffff2f.......
                ....f11222222222221f......
                .....f12fffffffff21f......
                .....8fffffffffffff8......
                .....ddfffffffffffdd......
                .....ddeeee...eeee........
                .......eeee1.1eeee........
                ......ffff1.1.1ffff.......
                .....ffffff1.1ffffff......
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """),
            img("""
                ..........................
                ..........................
                ..........................
                ..........................
                ........fffffffff.........
                ........222222222.........
                ....fffffffffffffffff.....
                ........eeedddfd..........
                .......ededdddfdddd.......
                .......edeeddddfdddd......
                .......eedddddfffff.......
                ........fddddddddd........
                ......8f21111111f.........
                ....dd8f1ffffff11f........
                ....dddffffffffff2fddd....
                ....dd.f2222222221f8dd....
                .......f2222fffff1f.f.....
                .......f22ffffffffeff.....
                .......f11fffffffeeff.....
                ........f1ffffffeeeff.....
                .........ffffff.eeeff.....
                ......1.eefff.......1.....
                .....1.1feeee......1.1....
                ......1fff..........1.....
                ........fff...............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """),
            img("""
                ..........................
                ..........................
                ..........................
                ..........................
                ........ffffffff..........
                ........22222222..........
                ....ffffffffffffffff......
                ........eeeddfd...........
                .......ededddfdddd........
                .......edeedddfdddd.......
                .......eeddddfffff........
                ........ddddddddd.........
                ........fffffff...........
                .......f111111fff.........
                .......f1ffff112f.........
                ......f2ffffff221f........
                ......f111222221ff........
                .......ff122222fff........
                ........ffff2ffff.........
                .........eeffffff.........
                ........1eeffee...........
                .......1.fffffff..........
                ........1ffffffff.........
                .........fff..............
                .........fff..............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """)],
        100,
        True)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_left_pressed():
    animation.run_image_animation(Wario,
        [img("""
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........ffffffff........
                ..........22222222........
                ......ffffffffffffffff....
                ..........dfdddeee........
                .......ddddfddddede.......
                ......ddddfddddeede.......
                .......fffffddddede.......
                ........dddddddddeff......
                .......f211111111122f.....
                .......f11ffffffff12f.....
                .......f2ffffffffff22f....
                ......f12222222222211f....
                ......f12fffffffff21f.....
                ......8fffffffffffff8.....
                ......ddfffffffffffdd.....
                ........eeee...eeeedd.....
                ........eeee1.1eeee.......
                .......ffff1.1.1ffff......
                ......ffffff1.1ffffff.....
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """),
            img("""
                ..........................
                ..........................
                ..........................
                ..........................
                .........fffffffff........
                .........222222222........
                .....fffffffffffffffff....
                ..........dfdddeee........
                .......ddddfddddede.......
                ......ddddfddddeede.......
                .......fffffdddddee.......
                ........dddddddddf........
                .........f11111112f8......
                ........f11ffffff1f8dd....
                ....dddf2ffffffffffddd....
                ....dd8f1222222222f.dd....
                .....f.f1fffff2222f.......
                .....ffeffffffff22f.......
                .....ffeefffffff11f.......
                .....ffeeeffffff1f........
                .....ffeee.ffffff.........
                .....1.......fffee.1......
                ....1.1......eeeef1.1.....
                .....1..........fff1......
                ...............fff........
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """),
            img("""
                ..........................
                ..........................
                ..........................
                ..........................
                ..........ffffffff........
                ..........22222222........
                ......ffffffffffffffff....
                ...........dfddeee........
                ........ddddfdddede.......
                .......ddddfdddeede.......
                ........fffffddddee.......
                .........ddddddddd........
                ...........fffffff........
                .........fff111111f.......
                .........f211ffff1f.......
                ........f122ffffff2f......
                ........ff122222111f......
                ........fff222221ff.......
                .........ffff2ffff........
                .........ffffffee.........
                ...........eeffee1........
                ..........fffffff.1.......
                .........ffffffff1........
                ..............fff.........
                ..............fff.........
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """)],
        100,
        True)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_left_released():
    animation.stop_animation(animation.AnimationTypes.ALL, Wario)
controller.left.on_event(ControllerButtonEvent.RELEASED, on_left_released)

def on_a_pressed():
    animation.run_image_animation(Wario,
        [img("""
                ..........................
                ..........................
                ..........................
                ..........................
                ..................1.......
                ..................111.....
                ...................112....
                ....................112...
                .....................11...
                ....................11....
                ...................111....
                ........ffffffff..dd1.....
                ........22222222..ddd.....
                ....ffffffffffffffffd.....
                ........eeedddfd..888.....
                .......ededdddfdddd88.....
                .......edeeddddfdddd8.....
                .......ededdddfffff8......
                ........eddddddddd8.......
                .....8888ffffffffff...f...
                ....88888f11111111ff..f...
                ...dd8888f1fffffff1feff...
                ...ddd.18fff22222f2feff...
                ....d.f.5ff22222222feff...
                .....fffeef11f222f1feff...
                ....fffeeeeffffff1ff.1.1..
                ....f..eeeee.ffffff...1...
                ....f.....................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """),
            img("""
                ..........................
                ..........................
                ..........................
                ..........................
                ........................11
                .......................111
                ......................111.
                .....................111..
                .....................11...
                ....................11....
                ...................111....
                ........ffffffff..dd1.....
                ........22222222..ddd.....
                ....ffffffffffffffffd.....
                ........eeedddfd..888.....
                .......ededdddfdddd88.....
                .......edeeddddfdddd8.....
                .......ededdddfffff8......
                ........eddddddddd8.......
                .....8888ffffffffff...f...
                ....88888f11111111ff..f...
                ...dd8888f1fffffff1feff...
                ...ddd.18fff22222f2feff...
                ....d.f.5ff22222222feff...
                .....fffeef11f222f1feff...
                ....fffeeeeffffff1ff.1.1..
                ....f..eeeee.ffffff...1...
                ....f.....................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """),
            img("""
                ..........................
                ..........................
                ..........................
                ..........................
                .....................1....
                ...................111....
                ..................211.....
                .................211......
                .................11.......
                ..................11......
                ..................111.....
                ........ffffffff..dd1.....
                ........22222222..ddd.....
                ....ffffffffffffffffd.....
                ........eeedddfd..888.....
                .......ededdddfdddd88.....
                .......edeeddddfdddd8.....
                .......ededdddfffff8......
                ........eddddddddd8.......
                .....8888ffffffffff...f...
                ....88888f11111111ff..f...
                ...dd8888f1fffffff1feff...
                ...ddd.18fff22222f2feff...
                ....d.f.5ff22222222feff...
                .....fffeef11f222f1feff...
                ....fffeeeeffffff1ff.1.1..
                ....f..eeeee.ffffff...1...
                ....f.....................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                """)],
        50,
        True)
    if Wario.is_hitting_tile(CollisionDirection.BOTTOM):
        Wario.vy = -325
    Wario.ay = 500
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_overlap_tile2(sprite2, location2):
    global monea
    if sprite2.tile_kind_at(TileDirection.TOP, assets.tile("""
        miMosaico22
        """)):
        tiles.set_tile_at(location2, assets.tile("""
            miMosaico25
            """))
        tiles.set_wall_at(location2, True)
        monea = sprites.create(img("""
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................444444444.......................
                .................4455555555544.....................
                ................455554444455554....................
                ...............4555bbbbbbbbb5554...................
                ..............4544b1dd111dd1b4454..................
                .............4544bdd1ddddd1ddbb444.................
                .............454bdd1111dd11dd11b44.................
                ............455b1ddddddddddddd1b55.................
                ............455b11ddd11111d1ddd1b5.................
                ............455b1dddd11d11ddddd1b4.................
                ............455bddd1ddddddd11dd1b4.................
                ............445bd1d11d1d1d1dd1d1b4.................
                ............445b1dd111ddd11111d1b4.................
                ............445b1111111111111111b4.................
                ............455b1111111111111111b4.................
                ............455b1111111111111111b5.................
                .............45b111dd1ddddd11111b4.................
                .............45b1111d1d1d1d1111b44.................
                ..............45b111d1d1d1d111b44..................
                ...............45b1dddddddd11b54...................
                ................45b11111111bb54....................
                .................44bbbbbbbb544.....................
                ...................444444444.......................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                ...................................................
                """),
            SpriteKind.food)
        tiles.place_on_tile(monea, location2)
        monea.x += -18
        sprites.destroy(monea, effects.smiles, 500)
    else:
        tiles.set_wall_at(location2, True)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        miMosaico22
        """),
    on_overlap_tile2)

def enemy1(xp: number, qo: number, rk: number):
    global gumbat
    gumbat = sprites.create(img("""
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ...................ffffffff.............
            ................fffddedddedfff..........
            ..............ffdde444e4beb4e4ff........
            .............fd444bebddddddebe44f.......
            ............fdebbdddd444444ddde4f.......
            ...........fdebdd4444444444444bf........
            ...........f4bd444444445ddddddf.........
            ..........fe4d44444445ddddbbbf..........
            .........fd4ed4444445dddbbbcf...........
            .........f4dd4444445dddbbbcf............
            .........f4d4444445dddbbbcf.............
            ........febd444445dddbbbcf..............
            .......fd4ed44445dddbbbcf...............
            .......fd4bd4445dddbbbcf................
            .......fe4d4445dddbbbcf.................
            .......fded444dddbbbcf..................
            .......fd4d445ddbbbcf...................
            .......fdbd44ddbbbcf....................
            .......feed44ddbbcf.....................
            .......fdbd44dbbcf......................
            ........f4e44dbcf.......................
            ........febd4dbf........................
            ........f44e4df.........................
            .........fe4bf..........................
            .........f44f...........................
            ..........ff............................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            ........................................
            """),
        SpriteKind.enemy)
    tiles.place_on_tile(gumbat, tiles.get_tile_location(xp, qo))
    gumbat.set_velocity(rk, -1)
    gumbat.set_bounce_on_wall(True)

def on_a_released():
    animation.stop_animation(animation.AnimationTypes.ALL, Wario)
controller.A.on_event(ControllerButtonEvent.RELEASED, on_a_released)

def on_overlap_tile3(sprite3, location3):
    if Wario.tile_kind_at(TileDirection.RIGHT, assets.tile("""
        miMosaico8
        """)):
        game.game_over(True)
    else:
        tiles.set_wall_at(location3, True)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        miMosaico8
        """),
    on_overlap_tile3)

def on_right_released():
    animation.stop_animation(animation.AnimationTypes.ALL, Wario)
controller.right.on_event(ControllerButtonEvent.RELEASED, on_right_released)

def on_overlap_tile4(sprite4, location4):
    if Wario.tile_kind_at(TileDirection.BOTTOM,
        assets.tile("""
            miMosaico24
            """)):
        game.game_over(False)
    else:
        tiles.set_wall_at(location4, True)
scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""
        miMosaico24
        """),
    on_overlap_tile4)

def on_on_overlap(sprite5, otherSprite):
    if Wario.vy > 10:
        sprites.destroy(otherSprite, effects.spray, 500)
        info.change_score_by(100)
    else:
        info.change_life_by(-3)
        scene.camera_shake(4, 500)
        music.play(music.create_sound_effect(WaveShape.NOISE,
                3300,
                1400,
                255,
                0,
                150,
                SoundExpressionEffect.WARBLE,
                InterpolationCurve.LINEAR),
            music.PlaybackMode.UNTIL_DONE)
        pause(500)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap)

monea: Sprite = None
gumbat: Sprite = None
Wario: Sprite = None
Wario = sprites.create(img("""
        ......ffffffff......
        ......ffffffff......
        ......22222222......
        ..ffffffffffffffff..
        ......eeedddfd......
        .....ededdddfdddd...
        .....edeeddddfdddd..
        .....ededdddfffff...
        ....ffeddddddddd....
        ...f221111111112f...
        ...f21ffffffff11f...
        ..f22ffffffffff2f...
        ..f11222222222221f..
        ...f12fffffffff21f..
        ...8fffffffffffff8..
        ...ddfffffffffffdd..
        ...ddeeee...eeee....
        .....eeee1.1eeee....
        ....ffff1.1.1ffff...
        ...ffffff1.1ffffff..
        """),
    SpriteKind.player)
velocidad = 100
corriendo = False
scene.camera_follow_sprite(Wario)
tiles.set_current_tilemap(tilemap("""
    nivel1
    """))
controller.move_sprite(Wario, 100, 0)
Wario.ay = 500
music.play(pianoRoll.create_song(hex("""
        00c8000308140100001c00010a006400f401640000040000000000000000000000000005000005f20100000400011104000800011108000c0001100c001000011110001400010f14001800011118001c00010d1c002000011120002400010c24002800011128002c0001093000340001113400380001093c00400001113c004000011540004400010c40004400010944004c00011544004c00011154005800011354005800011058006400011458006400011164006800011364006800011068006c00011468006c00011170007c00011470007c00011780008400011680008400011284008800011184008800011488009400011288009400010d9c00a0000116a000a4000116a400a8000116a800ac000116ac00b000010db000b4000111b400b8000116b800bc000114bc00c000010fc000c400010cc400c8000114c800cc000112cc00d000010dd000d400010ad400d8000112d800dc000111dc00e4000105dc00e4000109dc00e400010cdc00e4000111e400e8000105e800ec000108ec00f000010cf000f4000111f400fc000111f400fc000115f400fc00010cfc0004010115fc0004010111fc000401010c08010c01011308010c0101100c01180101140c011801011118011c01011318011c0101101c01200101111c012001011424012c01011724012c0101142c01340101162c013401011234013801011634013801011238013c01011438013c0101113c01480101123c014801010d
        """)),
    music.PlaybackMode.IN_BACKGROUND)
tiles.place_on_tile(Wario, tiles.get_tile_location(3, 78))
enemy1(12, 77, 30)
gumbat.ay = 500
enemy1(33, 77, 30)
gumbat.ay = 500
enemy1(45, 77, 30)
gumbat.ay = 500
enemy1(42, 77, 30)
gumbat.ay = 500
enemy1(75, 69, 30)
gumbat.ay = 500
enemy1(91, 77, 30)
gumbat.ay = 500
enemy1(118, 77, 30)
gumbat.ay = 500
enemy1(130, 77, 30)
gumbat.ay = 500
enemy1(179, 77, 30)
gumbat.ay = 500
